"""cambios

Revision ID: 033d71935b47
Revises: 
Create Date: 2024-02-26 16:04:55.586195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033d71935b47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuestionario_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuestionario_user', schema=None) as batch_op:
        batch_op.drop_column('total_points')

    # ### end Alembic commands ###
