"""db final

Revision ID: 73606e6b5f8d
Revises: 
Create Date: 2024-02-23 16:59:37.234755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73606e6b5f8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuestionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('inicio', sa.String(length=100), nullable=True),
    sa.Column('fin', sa.String(length=100), nullable=True),
    sa.Column('max_p', sa.Integer(), nullable=True),
    sa.Column('id_insignia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_insignia'], ['insignia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('foto', sa.String(length=100), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuestionario_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_cuestionario', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cuestionario'], ['cuestionario.id'], ),
    sa.ForeignKeyConstraint(['id_estado'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('id_cuestionario', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_cuestionario'], ['cuestionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('is_true', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_pregunta'], ['preguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cuestionario_user', sa.Integer(), nullable=False),
    sa.Column('id_opcion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cuestionario_user'], ['cuestionario_user.id'], ),
    sa.ForeignKeyConstraint(['id_opcion'], ['opciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuesta')
    op.drop_table('opciones')
    op.drop_table('preguntas')
    op.drop_table('cuestionario_user')
    op.drop_table('entidad')
    op.drop_table('cuestionario')
    op.drop_table('categoria')
    # ### end Alembic commands ###
