"""cambios

Revision ID: bdd76311443f
Revises: 
Create Date: 2024-03-28 11:45:42.343565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdd76311443f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entidad', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.alter_column('id_opcion',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rol')

    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.alter_column('id_opcion',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('entidad', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
