"""cambios

Revision ID: d96afbb60310
Revises: 7fc2fa24a5d6
Create Date: 2023-12-28 11:44:33.009430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96afbb60310'
down_revision = '7fc2fa24a5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensaje', sa.String(length=1000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_column('mensaje')

    # ### end Alembic commands ###
